on:
  push:
    branches:
      - main
    paths:
      - chill-viking-home/**
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [main]

name: test-chill-viking-home

permissions:
  contents: read

jobs:
  use-workflow:
    name: lint, test, and publish
    uses: chill-viking/workflows/.github/workflows/nx-sonar-cloud-scanner.yml@main
    with:
      sonar-project: chill-viking_swa-home
      working-directory: ./chill-viking-home/
      project-location: apps/home-landing
      coverage-location: coverage/lcov.info
      project-name: home-landing
      config-location: tsconfig.app.json
      project-version: 0.0.2
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
