on:
  push:
    branches:
      - main
    paths:
      - chill-viking-home/**
  pull_request:
    types: [ opened, synchronize, reopened ]

name: Scan chill-viking-home

permissions:
  contents: read

jobs:
  main:
    name: lint, test, and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chill-viking-home
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: chill-viking-home/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: chill-viking-home
          args: >
            -Dsonar.organization=chill-viking-org
            -Dsonar.projectKey=chill-viking_swa-home
            -Dsonar.javascript.lcov.reportPaths=coverage/chill-viking-home/lcov.info
            -Dsonar.typescript.tsconfigPaths=tsconfig.app.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
